name: appt_app
description: POT Flutter Appointment Application
version: 0.4.8

environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 
  intl: ^0.16.0
  provider: ^3.1.0
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^2.0.1
  google_maps_flutter: ^0.5.21
  carousel_slider: ^1.3.1
  shimmer: 1.0.0
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/best-barber.jpg
    - assets/images/barber-1.jpg
    - assets/images/Carlos.jpg
    - assets/images/Josue.jpg
    - assets/images/Jennifer.jpg 
    - assets/images/icons/apple-pay-48.png
    - assets/images/icons/visa-48.png
    - assets/images/icons/mastercard-48.png
    - assets/images/icons/american-express-48.png
    - assets/images/icons/twitter-48.png
    - assets/images/icons/facebook-logo.png
    - assets/images/icons/google-logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
